#!/usr/bin/env bash
# config
VERSION=0.1
ITERATION=1
VENDOR="sellorm"
LICENSE="MIT"
MAINTAINER="alsoran@5vcc.com"
URL="https://github.com/sellorm/alsoran"
DESCRIPTION="Command line tool to manage a local CRAN"

# set up functions

# display help
function help {
    echo "Error: no option specified."
    echo
    echo "Usage: $(basename ${0}) <all|clean|help>"
    echo
    echo "    all     builds the packages"
    echo "    clean   clean up downloaded pkg contents"
    echo "    help    this help text"
    echo ""
    echo "To build using a docker container use '$(basename ${0}) docker <all|clean|help>'"
    exit 1
}

# clean up afterwards
function clean {
  rm -rf ./*.rpm
  rm -rf ./*.deb
  exit 0
}

function buildDir {
  cd /build || exit 1
}

function checkBuildEnv {
  # check that fpm exists
  fpmExists=$(which fpm >/dev/null 2>&1 ; echo $?)
  if [[ ${fpmExists} -ne 0 ]];then
      echo 'fpm is not installed, exiting.'
      exit 1
  fi
}

function createRpm {
  # build the rpm
  # rpm -qpRi --provides --scripts ./pm2-2.4.2-1.x86_64.rpm
  fpm -s dir -t rpm -C ./src/ \
      --verbose \
      --name alsoran \
      --version ${VERSION} \
      --iteration ${ITERATION} \
      --vendor "${VENDOR}" \
      --license "${LICENSE}" \
      --maintainer "${MAINTAINER}" \
      --url "${URL}" \
      --description "${DESCRIPTION}" .
}

function createDeb {
  # build the deb
  fpm -s dir -t deb -C ./src/ \
      --verbose \
      --name alsoran \
      --version ${VERSION} \
      --iteration ${ITERATION} \
      --vendor "${VENDOR}" \
      --license "${LICENSE}" \
      --maintainer "${MAINTAINER}" \
      --url "${URL}" \
      --description "${DESCRIPTION}" .
}

function dockerBuild {
  shift 1
  BUILDOPTS="${@}"
  # docker run
  docker run -i -v ${PWD}:/build --entrypoint "/build/build" sellorm/build ${BUILDOPTS}
}

# check input params
case ${1} in
  all)
    buildDir
    checkBuildEnv
    createRpm
    createDeb
    exit 0
    ;;
  docker)
    dockerBuild "${@}"
    exit 0
    ;;
  clean)
    buildDir
    clean
    ;;
  help|*)
    help
    ;;
esac

help
